from dash.dash_table import FormatTemplate as FormatTemplate


defaultColDef = {
#  "filter": "agNumberColumnFilter",
"enableCellTxtSelection": True,
"ensureDomOrder": True,
 "resizable": True,
 "sortable": True,
 "editable": False,
 "floatingFilter": True,
}

JOBcolumnDefs =[
    {'headerName': 'application_id', 'field': 'application_id', 'filter': 'agTextColumnFilter'},
    {'headerName': 'application_date', 'field': 'application_date', 'filter': 'agTextColumnFilter'},
    {'headerName': 'company_name', 'field': 'company_name', 'filter': 'agTextColumnFilter'},
    {'headerName': 'job_title', 'field': 'job_title', 'filter': 'agTextColumnFilter'},
    {'headerName': 'location', 'field': 'location', 'filter': 'agTextColumnFilter'},
    {'headerName': 'office_participation', 'field': 'office_participation', 'filter': 'agTextColumnFilter'},
    {'headerName': 'role_desc', 'field': 'role_desc', 'filter': 'agTextColumnFilter'},
    {'headerName': 'responsibilities', 'field': 'responsibilities', 'filter': 'agTextColumnFilter'},
    {'headerName': 'requirements', 'field': 'requirements', 'filter': 'agTextColumnFilter'},
    {'headerName': 'pay_min', 'field': 'pay_min', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'pay_max', 'field': 'pay_max', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'cv_version', 'field': 'cv_version', 'filter': 'agTextColumnFilter'},
    {'headerName': 'cover_letter', 'field': 'cover_letter', 'filter': 'agTextColumnFilter'},
    {'headerName': 'self_assessment', 'field': 'self_assessment', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'core_skills', 'field': 'core_skills', 'filter': 'agTextColumnFilter'},
    {'headerName': 'llm', 'field': 'llm', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'mmm', 'field': 'mmm', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'marketing', 'field': 'marketing', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'retail', 'field': 'retail', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'healthcare', 'field': 'healthcare', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'finance', 'field': 'finance', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'senior_role', 'field': 'senior_role', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'staff_role', 'field': 'staff_role', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'generalist_role', 'field': 'generalist_role', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'management_role', 'field': 'management_role', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'recruiter_screen', 'field': 'recruiter_screen', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'recruiter_screen_date', 'field': 'recruiter_screen_date', 'filter': 'agTextColumnFilter'},
    {'headerName': 'hiring_manager_screen', 'field': 'hiring_manager_screen', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'hiring_manager_screen_date', 'field': 'hiring_manager_screen_date', 'filter': 'agTextColumnFilter'},
    {'headerName': 'technical_screen', 'field': 'technical_screen', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'technical_screen_date', 'field': 'technical_screen_date', 'filter': 'agTextColumnFilter'},
    {'headerName': 'offer', 'field': 'offer', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'offer_date', 'field': 'offer_date', 'filter': 'agTextColumnFilter'},
    {'headerName': 'rejection', 'field': 'rejection', 'filter': 'agNumberColumnFilter'},
    {'headerName': 'rejection_date', 'field': 'rejection_date', 'filter': 'agTextColumnFilter'},
    {'headerName': 'age', 'field': 'age', 'filter': 'agTextColumnFilter'},
    {'headerName': 'application_link', 'field': 'application_link', 'filter': 'agTextColumnFilter'},
    {'headerName': 'technical_screen_type', 'field': 'technical_screen_type', 'filter': 'agTextColumnFilter'},
    {'headerName': 'technical_screen_time', 'field': 'technical_screen_time', 'filter': 'agTextColumnFilter'}
    ]